name       : gd
version    : 2.2.3
release    : 7
source     :
    - https://github.com/libgd/libgd/releases/download/gd-2.2.3/libgd-2.2.3.tar.xz : 746b6cbd6769a22ff3ba6f5756f3512a769bd4cdf4695dff17f4867f25fa7d3c
license    : CUSTOM
component  : multimedia.graphics
summary    : GD Graphics Library
description: |
    GD is an open source code library for the dynamic creation of images by programmers.
emul32     : yes
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig(libpng)
    - pkgconfig32(libpng)
    - pkgconfig32(x11)
    - pkgconfig(libtiff-4)
    - pkgconfig32(libtiff-4)
    - pkgconfig(vpx)
    - pkgconfig32(vpx)
    - pkgconfig(xpm)
    - pkgconfig32(xpm)
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
    - libjpeg-turbo-devel
    - libjpeg-turbo-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2016-7568.patch
    ./bootstrap.sh
    %configure
build      : |
    %make
install    : |
    %make_install
