name       : gd
version    : 2.1.1
release    : 1
source     :
    - https://github.com/libgd/libgd/archive/gd-2.1.1.tar.gz : a68c69d2fe3eaab9db63b1c4d391dd549c26d3b47bfba484d5ed2d433c55d4d8
license    : CUSTOM
summary    : GD Graphics Library
description: |
    GD is an open source code library for the dynamic creation of images by programmers.
builddeps  : 
    - pkgconfig(libpng)
    - libjpeg-turbo-devel
    - pkgconfig(vpx)
    - pkgconfig(libtiff-4)
    - pkgconfig(xpm)
setup      : |
    ./bootstrap.sh
    %configure
build      : |
    %make
install    : |
    %make_install
