name       : gd
version    : 2.2.5
release    : 11
source     :
    - https://github.com/libgd/libgd/releases/download/gd-2.2.5/libgd-2.2.5.tar.xz : 8c302ccbf467faec732f0741a859eef4ecae22fea2d2ab87467be940842bde51
license    : BSD-3-Clause
component  : multimedia.graphics
summary    : GD Graphics Library
description: |
    GD is an open source code library for the dynamic creation of images by programmers.
emul32     : yes
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(libpng)
    - pkgconfig32(x11)
    - pkgconfig32(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig32(vpx)
    - pkgconfig32(xpm)
    - pkgconfig32(zlib)
    - libjpeg-turbo-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-5711.patch
    ./bootstrap.sh
    %configure
build      : |
    %make
install    : |
    %make_install
