name       : gd
version    : 2.1.1
release    : 4
source     :
    - https://github.com/libgd/libgd/archive/gd-2.1.1.tar.gz : a68c69d2fe3eaab9db63b1c4d391dd549c26d3b47bfba484d5ed2d433c55d4d8
license    : CUSTOM
component  : multimedia.graphics
summary    : GD Graphics Library
description: |
    GD is an open source code library for the dynamic creation of images by programmers.
emul32     : yes
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig(libpng)
    - pkgconfig32(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig32(libtiff-4)
    - pkgconfig(vpx)
    - pkgconfig32(vpx)
    - pkgconfig(xpm)
    - pkgconfig32(xpm)
    - glibc-32bit-devel
    - libgcc-32bit
    - libjpeg-turbo-devel
    - libjpeg-turbo-32bit-devel
setup      : |
    ./bootstrap.sh
    %configure
build      : |
    %make
install    : |
    %make_install
