name       : gd
version    : 2.3.0
release    : 15
source     :
    - https://github.com/libgd/libgd/releases/download/gd-2.3.0/libgd-2.3.0.tar.xz : ecd9155b9a417fb3f837f29e5966323796de247789163761dd72dbf83bfcac58
license    : BSD-3-Clause
component  : multimedia.graphics
summary    : GD Graphics Library
description: |
    GD is an open source code library for the dynamic creation of images by programmers.
emul32     : yes
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(libpng)
    - pkgconfig32(x11)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libwebp)
    - pkgconfig32(raqm)
    - pkgconfig32(vpx)
    - pkgconfig32(xpm)
    - pkgconfig32(zlib)
setup      : |
    cp $pkgfiles/getlib.sh config
    %patch -p1 < $pkgfiles/fix-gd-gd2-images-support.patch
    %patch -p1 < $pkgfiles/enable-all-formats-cmake.patch
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share
