name       : gd
version    : 2.3.2
release    : 16
source     :
    - https://github.com/libgd/libgd/releases/download/gd-2.3.2/libgd-2.3.2.tar.xz : 478a047084e0d89b83616e4c2cf3c9438175fb0cc55d8c8967f06e0427f7d7fb
license    : BSD-3-Clause
component  : multimedia.graphics
summary    : GD Graphics Library
description: |
    GD is an open source code library for the dynamic creation of images by programmers.
emul32     : yes
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libwebp)
    - pkgconfig32(raqm)
    - pkgconfig32(vpx)
    - pkgconfig32(x11)
    - pkgconfig32(xpm)
    - pkgconfig32(zlib)
    - pkgconfig(libheif)
setup      : |
    cp $pkgfiles/getlib.sh config
    if [[ -n "${EMUL32BUILD}" ]]; then
        _heif=OFF
    else
        _heif=ON
    fi
    %cmake_ninja \
        -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DENABLE_GD_FORMATS=ON \
        -DENABLE_FONTCONFIG=ON \
        -DENABLE_FREETYPE=ON \
        -DENABLE_HEIF=$_heif \
        -DENABLE_ICONV=ON \
        -DENABLE_JPEG=ON \
        -DENABLE_PNG=ON \
        -DENABLE_RAQM=ON \
        -DENABLE_TIFF=ON \
        -DENABLE_WEBP=ON \
        -DENABLE_XPM=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share
